const actions = {
    UPDATE_NEW_PROJECT_TEXT : "UPDATE_NEW_PROJECT_TEXT",
    ADD_NEW_PROJECT : "ADD_NEW_PROJECT",
    ADD_INPUT_TASKS : "ADD_INPUT_TASKS",
    MOVE_CARD_TO_ARCHIVE: "MOVE_CARD_TO_ARCHIVE",
    MOVE_CARD_TO_INPROCASS: "MOVE_CARD_TO_INPROCASS",
    DELETE_PROJECT: "DELETE_PROJECT" ,
    MOVE_IN_NOT_DONE: "MOVE_IN_NOT_DONE",
    MOVE_TO_DONE: "MOVE_TO_DONE"
}


export default actions;